#include <string.h>
#include <stdlib.h>

int load_frames(char*** frames, int** delays) {
    int i;
    *frames = malloc(5 * sizeof(char*));
    
    for (i = 0; i < 5; i++) {
        (*frames)[i] = malloc(10000 * sizeof(char));
    }

    strncpy((*frames)[0],
            "TTTTTTTT  UU    UU\n"
            "   TT     UU    UU\n"
            "   TT      UU  UU\n"
            "   TT       UUUU\n"
            "\n"
            "                         __________\n"
            "                   .ooooTOOOOOOOOOOToo..\n"
            "                _./OOOOOOOOOOOOOOOOO****\\._\n"
            "              ./OOOOOOOOOOOOOOOOOOO********\\._\n"
            "            ./OOOOOOOOOOOOOOOOOOOOO***********\\._\n"
            "           /OOOOOOOOOOOOOOOOOOOOOOOO*************\\.\n"
            "     _____/^^^^^^^^TTTTTPPPVTTTOOOOOO**************\\.\n"
            "    |*****\\OOOOOO/Ooooooo..._____-\\p****************L\n"
            "  ./*******\\OOOO/OOO9/^¨^VOOOOOOOO\\-'''''\\***********|\n"
            " /********T/\\OO|OO/        '^-VOOOOOOOOOO\\..\\********|\n"
            "|********/:/ '\\U/   _*##*-    |:7TOOOOOOOOOA..\\****.V\n"
            " \\******/:/        *.-^^-.   .|:::\\OOOOOO^vOOA..\\*/\n"
            "  \\LLLL/::_\\      .//a\\.'.^. /:::::^PPv/:::\\VOVOVOA-.\n"
            "      /::|0.|     | Y0/.'./  /::::::::::::::::| \\OOOO\\\n"
            "      |::\\./       ^--..-'  /::::::::::::\\:::::  \\OOOO\\\n"
            "       .-^                ./::::::::::::::;:::::\\ \\OOOO\\\n"
            "       \\                 /::./|:::::::::::\\:::::\\  ^-T-^\n"
            "        )              .^.-^ .|::::::::::::^:::::\\\n"
            "        /                    /.^\\:::::::::::\\:::::\\\n"
            "        |/^-                /   .^:::./\\::::|\\::::\\\n"
            "        \\\\.-^                   /::./::.\\:::| \\::::\\\n"
            "         )                     /::/\\:::|\\:::.| \\.:::\\\n"
            "         |                   ./:.^  \\:/  Y:::|   \\.::\\\n"
            "         (__                /.-^\\    V   \\:::|     \\.:\\\n"
            "       ./:::^^^^-----.           \\        \\:/        \\.\\\n"
            "       /::/\\::::::./  \\           \\        V          ^-.\n"
            "      /:/.  \\:::./     \\           \\\n"
            "      V^    |:./       .|\n"
            "           /./          \\\n"
            "           V\n", 10000);

    strncpy((*frames)[1],
            "TTTTTTTT  UU    UU  TTTTTTTT  UU    UU\n"
            "   TT     UU    UU     TT     UU    UU\n"
            "   TT      UU  UU      TT      UU  UU\n"
            "   TT       UUUU       TT       UUUU\n"
            "\n"
            "                         __________\n"
            "                   .ooooTOOOOOOOOOOToo..\n"
            "                _./OOOOOOOOOOOOOOOOO****\\._\n"
            "              ./OOOOOOOOOOOOOOOOOOO********\\._\n"
            "            ./OOOOOOOOOOOOOOOOOOOOO***********\\._\n"
            "           /OOOOOOOOOOOOOOOOOOOOOOOO*************\\.\n"
            "     _____/^^^^^^^^TTTTTPPPVTTTOOOOOO**************\\.\n"
            "    |*****\\OOOOOO/Ooooooo..._____-\\p****************L\n"
            "  ./*******\\OOOO/OOO9/^¨^VOOOOOOOO\\-'''''\\***********|\n"
            " /********T/\\OO|OO/        '^-VOOOOOOOOOO\\..\\********|\n"
            "|********/:/ '\\U/   _*##*-    |:7TOOOOOOOOOA..\\****.V\n"
            " \\******/:/        *.-^^-.   .|:::\\OOOOOO^vOOA..\\*/\n"
            "  \\LLLL/::_\\      .//a\\.'.^. /:::::^PPv/:::\\VOVOVOA-.\n"
            "      /::|0.|     | Y0/.'./  /::::::::::::::::| \\OOOO\\\n"
            "      |::\\./       ^--..-'  /::::::::::::\\:::::  \\OOOO\\\n"
            "       .-^                ./::::::::::::::;:::::\\ \\OOOO\\\n"
            "       \\                 /::./|:::::::::::\\:::::\\  ^-T-^\n"
            "        )              .^.-^ .|::::::::::::^:::::\\\n"
            "        /                    /.^\\:::::::::::\\:::::\\\n"
            "        |.-_                /   .^:::./\\::::|\\::::\\\n"
            "        \\\\-^                    /::./::.\\:::| \\::::\\\n"
            "         )                     /::/\\:::|\\:::.| \\.:::\\\n"
            "         |                   ./:.^  \\:/  Y:::|   \\.::\\\n"
            "         (__                /.-^\\    V   \\:::|     \\.:\\\n"
            "       ./:::^^^^-----.           \\        \\:/        \\.\\\n"
            "       /::/\\::::::./  \\           \\        V          ^-.\n"
            "      /:/.  \\:::./     \\           \\\n"
            "      V^    |:./       .|\n"
            "           /./          \\\n"
            "           V\n", 10000);

    strncpy((*frames)[2],
"TTTTTTTT  UU    UU  TTTTTTTT  UU    UU  RRRRR   UU    UU  /\\\n"
"   TT     UU    UU     TT     UU    UU  RR  RR  UU    UU  \\/\n"
"   TT      UU  UU      TT      UU  UU   RRRRR    UU  UU\n"
"   TT       UUUU       TT       UUUU    RR  RR    UUUU    ()\n"
"\n"
"                         __________\n"
"                   .ooooTOOOOOOOOOOToo..\n"
"                _./OOOOOOOOOOOOOOOOO****\\._\n"
"              ./OOOOOOOOOOOOOOOOOOO********\\._\n"
"            ./OOOOOOOOOOOOOOOOOOOOO***********\\._\n"
"           /OOOOOOOOOOOOOOOOOOOOOOOO*************\\.\n"
"     _____/^^^^^^^^TTTTTPPPVTTTOOOOOO**************\\.\n"
"    |*****\\OOOOOO/Ooooooo..._____-\\p****************L\n"
"  ./*******\\OOOO/OOO9/^¨^VOOOOOOOO\\-'''''\\***********|\n"
" /********T/\\OO|OO/        '^-VOOOOOOOOOO\\..\\********|\n"
"|********/:/ '\\U/   _*##*-    |:7TOOOOOOOOOA..\\****.V\n"
" \\******/:/        *.-^^-.   .|:::\\OOOOOO^vOOA..\\*/\n"
"  \\LLLL/::_\\      .//a\\.'.^. /:::::^PPv/:::\\VOVOVOA-.\n"
"      /::|0.|     | Y0/.'./  /::::::::::::::::| \\OOOO\\\n"
"      |::\\./       ^--..-'  /::::::::::::\\:::::  \\OOOO\\\n"
"       .-^                ./::::::::::::::;:::::\\ \\OOOO\\\n"
"       \\                 /::./|:::::::::::\\:::::\\  ^-T-^\n"
"        )              .^.-^ .|::::::::::::^:::::\\\n"
"        /                    /.^\\:::::::::::\\:::::\\\n"
"        |/^-                /   .^:::./\\::::|\\::::\\\n"
"        \\\\.-^                   /::./::.\\:::| \\::::\\\n"
"         )                     /::/\\:::|\\:::.| \\.:::\\\n"
"         |                   ./:.^  \\:/  Y:::|   \\.::\\\n"
"         (__                /.-^\\    V   \\:::|     \\.:\\\n"
"       ./:::^^^^-----.           \\        \\:/        \\.\\\n"
"       /::/\\::::::./  \\           \\        V          ^-.\n"
"      /:/.  \\:::./     \\           \\\n"
"      V^    |:./       .|\n"
"           /./          \\\n"
"           V\n", 10000);

    strncpy((*frames)[3],
"TTTTTTTT  UU    UU  TTTTTTTT  UU    UU  RRRRR   UU    UU  /\\\n"
"   TT     UU    UU     TT     UU    UU  RR  RR  UU    UU  \\/\n"
"   TT      UU  UU      TT      UU  UU   RRRRR    UU  UU\n"
"   TT       UUUU       TT       UUUU    RR  RR    UUUU    ()\n"
"\n"
"                         __________\n"
"                   .ooooTOOOOOOOOOOToo..\n"
"                _./OOOOOOOOOOOOOOOOO****\\._\n"
"              ./OOOOOOOOOOOOOOOOOOO********\\._\n"
"            ./OOOOOOOOOOOOOOOOOOOOO***********\\._\n"
"           /OOOOOOOOOOOOOOOOOOOOOOOO*************\\.\n"
"     _____/^^^^^^^^TTTTTPPPVTTTOOOOOO**************\\.\n"
"    |*****\\OOOOOO/Ooooooo..._____-\\p****************L\n"
"  ./*******\\OOOO/OOO9/^¨^VOOOOOOOO\\-'''''\\***********|\n"
" /********T/\\OO|OO/        '^-VOOOOOOOOOO\\..\\********|\n"
"|********/:/ '\\U/             |:7TOOOOOOOOOA..\\****.V\n"
" \\******/:/         .*##*--  .|:::\\OOOOOO^vOOA..\\*/\n"
"  \\LLLL/:: \\      .--'^^^\\   /:::::^PPv/:::\\VOVOVOA-.\n"
"      /::|o-|     \\ Y0__'.>  /::::::::::::::::| \\OOOO\\\n"
"      |::\\./       ^^^  ^   /::::::::::::\\:::::  \\OOOO\\\n"
"       .-^                ./::::::::::::::;:::::\\ \\OOOO\\\n"
"       \\                 /::./|:::::::::::\\:::::\\  ^-T-^\n"
"        )              .^.-^ .|::::::::::::^:::::\\\n"
"        /          .::       /.^\\:::::::::::\\:::::\\\n"
"        |.--        ::      /   .^:::./\\::::|\\::::\\\n"
"        \\'-^'                   /::./::.\\:::| \\::::\\\n"
"         )                     /::/\\:::|\\:::.| \\.:::\\\n"
"         |                   ./:.^  \\:/  Y:::|   \\.::\\\n"
"         (__                /.-^\\    V   \\:::|     \\.:\\\n"
"       ./:::^^^^-----.           \\        \\:/        \\.\\\n"
"       /::/\\::::::./  \\           \\        V          ^-.\n"
"      /:/.  \\:::./     \\           \\\n"
"      V^    |:./       .|\n"
"           /./          \\\n"
"           V\n", 10000);
    strncpy((*frames)[4],
"TTTTTTTT  UU    UU  TTTTTTTT  UU    UU  RRRRR   UU    UU  /\\\n"
"   TT     UU    UU     TT     UU    UU  RR  RR  UU    UU  \\/\n"
"   TT      UU  UU      TT      UU  UU   RRRRR    UU  UU\n"
"   TT       UUUU       TT       UUUU    RR  RR    UUUU    ()\n"
"\n"
"                         __________\n"
"                   .ooooTOOOOOOOOOOToo..\n"
"                _./OOOOOOOOOOOOOOOOO****\\._\n"
"              ./OOOOOOOOOOOOOOOOOOO********\\._\n"
"            ./OOOOOOOOOOOOOOOOOOOOO***********\\._\n"
"           /OOOOOOOOOOOOOOOOOOOOOOOO*************\\.\n"
"     _____/^^^^^^^^TTTTTPPPVTTTOOOOOO**************\\.\n"
"    |*****\\OOOOOO/Ooooooo..._____-\\p****************L\n"
"  ./*******\\OOOO/OOO9/^¨^VOOOOOOOO\\-'''''\\***********|\n"
" /********T/\\OO|OO/        '^-VOOOOOOOOOO\\..\\********|\n"
"|********/:/ '\\U/             |:7TOOOOOOOOOA..\\****.V\n"
" \\******/:/                  .|:::\\OOOOOO^vOOA..\\*/\n"
"  \\LLLL/:: \\      .-.*##*-.  /:::::^PPv/:::\\VOVOVOA-.\n"
"      /::|.-|       .---..   /::::::::::::::::| \\OOOO\\\n"
"      |::\\./       ^      ^ /::::::::::::\\:::::  \\OOOO\\\n"
"       .-^                ./::::::::::::::;:::::\\ \\OOOO\\\n"
"       \\           .:.   /::./|:::::::::::\\:::::\\  ^-T-^\n"
"        )         .:::..^.-^ .|::::::::::::^:::::\\\n"
"        /         .::::      /.^\\:::::::::::\\:::::\\\n"
"        |__..,     .:::.    /   .^:::./\\::::|\\::::\\\n"
"        \\'^^'        ''         /::./::.\\:::| \\::::\\\n"
"         )                     /::/\\:::|\\:::.| \\.:::\\\n"
"         |                   ./:.^  \\:/  Y:::|   \\.::\\\n"
"         (__                /.-^\\    V   \\:::|     \\.:\\\n"
"       ./:::^^^^-----.           \\        \\:/        \\.\\\n"
"       /::/\\::::::./  \\           \\        V          ^-.\n"
"      /:/.  \\:::./     \\           \\\n"
"      V^    |:./       .|\n"
"           /./          \\\n"
"           V\n", 10000);

    (*delays) = malloc(5 * sizeof(int));
    (*delays)[0] = 300000;
    (*delays)[1] = 200000;
    (*delays)[2] = 1000000;
    (*delays)[3] = 100000;
    (*delays)[4] = 1000000;
    
    return 5;
}
